apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch6
  labels: 
    app: elasticsearch6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch6
  template:
    metadata:
      labels:
        app: elasticsearch6
    spec:
      containers:
      - name: elasticsearch6
        image: harbor.wow-trend.us/wow/elasticsearch:v6.3.2
        imagePullPolicy: Always
        command: ["bash", "-c", "ulimit -l unlimited && sysctl -w vm.max_map_count=262144 && exec su elasticsearch docker-entrypoint.sh"]
        env:
        - name: "discovery.zen.minimum_master_nodes"
          value: "1"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1024m -Xmx1024m"
        - name: "discovery.type"
          value: "single-node"
        ports:
        - name: http 
          containerPort: 9200
        - name: trans
          containerPort: 9300
        securityContext:
          privileged: true
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-data
        nfs:
          path: /data/k8s-nfs/data/elasticsearch
          server: 192.168.1.6
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch6
  type: NodePort
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 9200
  - name: trans
    port: 9300
    protocol: TCP
    targetPort: 9300
    nodePort: 9300
