apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels: 
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: harbor.wow-trend.us/wow/jenkins:v2.150
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/ssh-keygen.sh && /ssh-copy-id.sh"]
      volumes:
      - name: jenkins-data
        nfs:
          path: /data/k8s-nfs/data/jenkins
          server: 192.168.1.6
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node03
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins
    port: 8080
    protocol: TCP
    targetPort: 8080
