apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels: 
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        kubernetes.io/hostname: node04
      containers:
      - name: jenkins
        image: harbor.wow-trend.us/wow/jenkins:v2.150
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-data
        nfs:
          path: /data/k8s-nfs/data/jenkins
          server: 192.168.1.6
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - name: jenkins
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 8081
