apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash6
  labels: 
    app: logstash6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash6
  template:
    metadata:
      labels:
        app: logstash6
    spec:
      containers:
      - name: logstash6
        image: harbor.wow-trend.us/wow/logstash:v6.3.2
        ports:
        - containerPort: 9600
        securityContext:
          privileged: true
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir /usr/share/logstash/cache"]
      volumes:
      - name: logstash-config
        nfs:
          path: /data/k8s-nfs/config/logstash
          server: 192.168.1.6
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node04
