apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels: 
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: harbor.wow-trend.us/wow/mongodb:v4.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 200Gi
      storageClassName: nfs-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  clusterIP: None
  ports:
  - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
spec:
  ports:
  - nodePort: 27017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: NodePort
