apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    nodePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: tengine
        image: harbor.wow-trend.us/wow/tengine:v2.3.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html
        - name: nginx-conf
          mountPath: /etc/nginx/sites-enabled
        - name: nginx-log
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-data
        nfs:
          path: /data/k8s-nfs/data/wwwroot
          server: 192.168.1.6
      - name: nginx-conf
        nfs:
          path: /data/k8s-nfs/config/nginx
          server: 192.168.1.6
      - name: nginx-log
        nfs:
          path: /data/k8s-nfs/log/nginx
          server: 192.168.1.6
