apiVersion: v1
kind: Service
metadata:
  name: php5
spec:
  selector:
    app: php5-server
  ports:
  - name: php5
    port: 9000
    targetPort: 9000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php5-server
  labels:
    name: php5-server
spec:
  replicas: 1
  selector:
    matchLabels:
        app: php5-server
  template:
    metadata:
      labels:
        app: php5-server
    spec:
      containers:
      - name: php5
        image: harbor.wow-trend.us/wow/php5-fpm:v5.6
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/www/html/
          name: webdata
        ports:
        - containerPort: 9001
      volumes:
      - name: webdata
        nfs:
          path: /data/k8s-nfs/data/wwwroot
          server: 192.168.1.6
