apiVersion: v1
kind: Service
metadata:
  name: php7-nginx
spec:
  selector:
    app: php7-nginx
  ports:
  - name: php7-nginx
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php7-nginx
  labels:
    name: php7-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
        app: php7-nginx
  template:
    metadata:
      labels:
        app: php7-nginx
    spec:
      containers:
      - name: php7
        image: harbor.wow-trend.us/wow/php-fpm:v7.3
      #  imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
        - name: "REDIS_PORT"
          value: "6379"
        volumeMounts:
        - mountPath: /var/www/html/
          name: webdata
        ports:
        - containerPort: 9000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cd /var/www/html/service.wow-trend.com && nohup php artisan queue:work &"]
      - name: tengine
        image: harbor.wow-trend.us/wow/tengine:v2.3.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdata
          mountPath: /var/www/html
        - name: nginx-conf
          mountPath: /etc/nginx/sites-enabled
        - name: nginx-log
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-conf
        nfs:
          path: /data/k8s-nfs/config/nginx
          server: 192.168.1.6
      - name: nginx-log
        nfs:
          path: /data/k8s-nfs/log/nginx
          server: 192.168.1.6
      - name: webdata
        nfs:
          path: /data/k8s-nfs/data/wwwroot
          server: 192.168.1.6
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: php7-nginx
spec:
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: php7-nginx
          servicePort: 80
