apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-100
  labels:
    name: pv-100
spec:
  nfs:
    path: /data/k8s-nfs/data/mysql-pv-100
    server: 192.168.1.6
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  capacity:
    storage: 100Gi
  storageClassName: nfs-mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-100
  labels:
    name: pv-100
spec:
  nfs:
    path: /data/k8s-nfs/data/es-pv-100
    server: 192.168.1.6
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  capacity:
    storage: 100Gi
  storageClassName: nfs-es
