apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-100-1
  labels:
    name: pv-100
spec:
  nfs:
    path: /data/k8s-nfs/data/pv-100-1
    server: 192.168.1.6
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  capacity:
    storage: 100Gi
  storageClassName: nfs-mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-100-2
  labels:
    name: pv-100
spec:
  nfs:
    path: /data/k8s-nfs/data/pv-100-2
    server: 192.168.1.6
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  capacity:
    storage: 100Gi
