apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels: 
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: harbor.wow-trend.us/wow/redis:v4.0
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-server
  type: NodePort
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 6379
