apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaoyaoji
  labels: 
    app: xiaoyaoji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiaoyaoji
  template:
    metadata:
      labels:
        app: xiaoyaoji
    spec:
      containers:
      - name: xiaoyaoji
        image: harbor.wow-trend.us/wow/xiaoyaoji:v2.1.5
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node02
---
apiVersion: v1
kind: Service
metadata:
  name: xiaoyaoji
spec:
  selector:
    app: xiaoyaoji
  ports:
  - name: xiaoyaoji
    port: 8080
    protocol: TCP
    targetPort: 8080
