apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaoyaoji
  labels: 
    app: xiaoyaoji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiaoyaoji
  template:
    metadata:
      labels:
        app: xiaoyaoji
    spec:
      nodeSelector:
        kubernetes.io/hostname: node04
      containers:
      - name: xiaoyaoji
        image: harbor.wow-trend.us/wow/xiaojaoji:v2.1.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xiaoyaoji
spec:
  selector:
    app: xiaoyaoji
  type: NodePort
  ports:
  - name: xiaoyaoji
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 8080
