apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitor
  name: alert-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['node']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://127.0.0.1:5000/ding'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitor
  name: rules
data:
  alert-rules.yml: |
    groups:
    - name: node-rules
      rules:
      - alert: InstanceDown  # 实例存活性告警
        expr: up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "告警：Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
      - alert: MemoryUsage   # 内存使用率告警
        expr: 100 - node_memory_MemAvailable_bytes * 100 / node_memory_MemTotal_bytes > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "告警：Instance {{ $labels.instance }} memory usage is too high"
          description: "Lack of available memory on {{ $labels.instance }}, current value is: {{ $value }}%"
      - alert: CPUUsage   # CPU使用率告警
        expr: (((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode="idle"}) by (cpu)) > 90
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "告警：Instance {{ $labels.instance }} cpu is busy"
          description: "CPU load is above 90% on {{ $labels.instance }}, current value is: {{ $value }}%"
      - alert: FilesystemUsage   # 硬盘使用率告警
        expr: (1-(node_filesystem_free_bytes{mountpoint!~"/boot",fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"}))*100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "告警：Instance {{ $labels.instance }} disk space is not enough"
          description: "Disk space is used over 90% on {{ $labels.instance }}, mountpoint is: {{ $labels.mountpoint }}, current value is: {{ $value }}%"
    - name: mysql-rules
      rules:
      - alert: MysqlConnections  # mysql连接数
        expr: mysql_global_status_max_used_connections > 250
        for: 1m
        annotations:
          summary: "告警：Instance {{ $labels.instance }} mysql too many connections detected"
          description: "Mysql used connections is more than 250 on {{ $labels.instance }}, current value is: {{ $value }}"
