apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitor
  name: prome-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets: ['localhost:9093']

    rule_files:
      - 'alert-rules.yml'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'node'
        static_configs:
        - targets: ['192.168.1.10:9100', '192.168.1.8:9100', '192.168.1.33:9100', '192.168.1.6:9100', '192.168.8.168:9100', '192.168.8.88:9100', '192.168.8.170:9100', '192.168.8.169:9100', '192.168.1.18:9100', '192.168.1.15:9100', '192.168.1.11:9100', '192.168.1.16:9100', '192.168.1.24:9182', '192.168.1.168:9100', '192.168.1.169:9100', '192.168.1.170:9100', '192.168.1.171:9100']
      - job_name: 'mysql'
        static_configs:
        - targets: ['192.168.1.18:9104', '192.168.1.16:9104']
      - job_name: 'nodes-cadvisor'
        kubernetes_sd_configs:
        - role: node
          api_server: https://192.168.1.168:6443
          tls_config:
            insecure_skip_verify: true
          bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ii1nRGV3QkJOSVdRdUgyLURRU1RvZkVzRTU3aTFLU1FWRk1jTlJPNnJRUEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFkbWluLXRva2VuLTViZDlsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmJhOTFkZTQtMjE2My00MTRkLWI5YzYtZTFkZDJjNzZkZDM2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YWRtaW4ifQ.g4OeTNPLsBnC7QImvhrqkVLuByBt9BFJ1H3AtzO__5h-L0zQ8T7wZDPNwwmf8DT6hXs2HDQ9c66m8dc2kg7FxrxpoeN9noyHxo01GwMKhcUfIQRm1ow_YhxXEqGHQWDK4xxdwcZSvzeLb-CkVZ5H2UwEOQpe1tuQQVHJovqyCsA7kXrRo2KykjxcEI-_Y69Lp88OyWq2_cbwEx5ipVaXrG_28p4ost3OR4EKk37GdX8xbew0pU2ca45d52Q6Q3pSksryrJZCEdAp9IFy5cXIFmzdOTKXV9QvZ3B76gLz-uK2AAKgxqmuVmI0jLvBHX6NIhHMLKyYnhmNFyf1w2pJJw
        tls_config:
          insecure_skip_verify: true
        bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ii1nRGV3QkJOSVdRdUgyLURRU1RvZkVzRTU3aTFLU1FWRk1jTlJPNnJRUEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFkbWluLXRva2VuLTViZDlsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmJhOTFkZTQtMjE2My00MTRkLWI5YzYtZTFkZDJjNzZkZDM2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YWRtaW4ifQ.g4OeTNPLsBnC7QImvhrqkVLuByBt9BFJ1H3AtzO__5h-L0zQ8T7wZDPNwwmf8DT6hXs2HDQ9c66m8dc2kg7FxrxpoeN9noyHxo01GwMKhcUfIQRm1ow_YhxXEqGHQWDK4xxdwcZSvzeLb-CkVZ5H2UwEOQpe1tuQQVHJovqyCsA7kXrRo2KykjxcEI-_Y69Lp88OyWq2_cbwEx5ipVaXrG_28p4ost3OR4EKk37GdX8xbew0pU2ca45d52Q6Q3pSksryrJZCEdAp9IFy5cXIFmzdOTKXV9QvZ3B76gLz-uK2AAKgxqmuVmI0jLvBHX6NIhHMLKyYnhmNFyf1w2pJJw
        scheme: https
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: 192.168.1.168:6443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - job_name: 'kube-state-metrics'
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
        - role: endpoints
          api_server: https://192.168.1.168:6443
          bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ii1nRGV3QkJOSVdRdUgyLURRU1RvZkVzRTU3aTFLU1FWRk1jTlJPNnJRUEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFkbWluLXRva2VuLTViZDlsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmJhOTFkZTQtMjE2My00MTRkLWI5YzYtZTFkZDJjNzZkZDM2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YWRtaW4ifQ.g4OeTNPLsBnC7QImvhrqkVLuByBt9BFJ1H3AtzO__5h-L0zQ8T7wZDPNwwmf8DT6hXs2HDQ9c66m8dc2kg7FxrxpoeN9noyHxo01GwMKhcUfIQRm1ow_YhxXEqGHQWDK4xxdwcZSvzeLb-CkVZ5H2UwEOQpe1tuQQVHJovqyCsA7kXrRo2KykjxcEI-_Y69Lp88OyWq2_cbwEx5ipVaXrG_28p4ost3OR4EKk37GdX8xbew0pU2ca45d52Q6Q3pSksryrJZCEdAp9IFy5cXIFmzdOTKXV9QvZ3B76gLz-uK2AAKgxqmuVmI0jLvBHX6NIhHMLKyYnhmNFyf1w2pJJw
          tls_config:
            insecure_skip_verify: true
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          separator: ;
          regex: https-self
          replacement: $1
          action: keep
        - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
          separator: ;
          regex: Node;(.*)
          target_label: node
          replacement: ${1}
          action: replace
        - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
          separator: ;
          regex: Pod;(.*)
          target_label: pod
          replacement: ${1}
          action: replace
        - source_labels: [__meta_kubernetes_namespace]
          separator: ;
          regex: (.*)
          target_label: namespace
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_service_name]
          separator: ;
          regex: (.*)
          target_label: service
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          target_label: pod
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_service_name]
          separator: ;
          regex: (.*)
          target_label: job
          replacement: ${1}
          action: replace
        - source_labels: [__meta_kubernetes_service_label_k8s_app]
          separator: ;
          regex: (.+)
          target_label: job
          replacement: ${1}
          action: replace
        - separator: ;
          regex: (.*)
          target_label: endpoint
          replacement: https-self
          action: replace
        - source_labels: [__address__]
          action: replace
          target_label: instance
        - target_label: __address__
          replacement: 192.168.1.168:8080
